export const API_STATUS = {
    OK: "OK",
    NOT_FOUND: "NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    AUTHENTICATE: "AUTHENTICATE",
    DB_ERROR: "DB_ERROR",
    INVALID_INPUT: "INVALID_INPUT",
    EXISTED: "EXISTED",
    NOT_VERIFIED: "NOT_VERIFIED",
};

export const HTTP_METHOD = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    DELETE: "DELETE",
};
